alias radio-franceinfo="mplayer http://direct.franceinfo.fr/live/franceinfo-midfi.mp3"
alias radio-francemusique="mplayer http://direct.francemusique.fr/live/francemusique-midfi.mp3"
alias radio-franceinter="mplayer http://direct.franceinter.fr/live/franceinter-midfi.mp3"
alias radio-franceculture="mplayer http://direct.franceculture.fr/live/franceculture-midfi.mp3"
alias radio-fip="mplayer http://direct.fipradio.fr/live/fip-midfi.mp3"
alias radio-rtl2="mplayer http://streaming.radio.rtl.fr/rtl2-1-44-64.mp3"
alias radio-nova="mplayer http://broadcast.infomaniak.net/radionova-high.mp3"
alias radio-mouv="mplayer http://direct.mouv.fr/live/mouv-midfi.mp3"
