alias radio-france-info="mplayer http://direct.franceinfo.fr/live/franceinfo-midfi.mp3"
alias radio-france-musique="mplayer http://direct.francemusique.fr/live/francemusique-midfi.mp3"
alias radio-france-inter="mplayer http://direct.franceinter.fr/live/franceinter-midfi.mp3"
alias radio-france-culture="mplayer http://direct.franceculture.fr/live/franceculture-midfi.mp3"
alias radio-fip="mplayer http://direct.fipradio.fr/live/fip-midfi.mp3"
alias radio-rtl2="mplayer http://streaming.radio.rtl.fr/rtl2-1-44-64.mp3"
alias radio-nova="mplayer http://broadcast.infomaniak.net/radionova-high.mp3"
alias radio-mouv="mplayer http://direct.mouv.fr/live/mouv-midfi.mp3"
alias radio-meuh="mplayer -playlist http://radiomeuh.ice.infomaniak.ch/radiomeuh-64.aac.m3u" 
alias radio-europe1="mplayer http://mp3lg3.scdn.arkena.com/10489/europe1.mp3" 
alias radio-classique="mplayer http://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3" 
alias radio-rire-et-chansons-sketches="mplayer http://185.52.127.157/fr/30407/mp3_128.mp3?origine=fluxradios" 
alias radio-rtl="mplayer http://streaming.radio.rtl.fr/rtl-1-44-128"
alias radio-sing-sing="mplayer http://stream.sing-sing.org:8000/singsing128" 
