#!/bin/sh
#
# update
#
# `update` handles installation, updates, things like that. Run it
# periodically to make sure you're on the latest and greatest.
export ZSH="$HOME/.dotfiles"

OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    alias ls='ls --color=auto'
    ;;
  'FreeBSD')
    OS='FreeBSD'
    alias ls='ls -G'
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin')
    OS='Mac'
    # Set OS defaults
    "$ZSH/config/osx/set-defaults.sh"
    # Install homebrew
    "$ZSH/config/homebrew/install.sh" 2>&1
    ;;
  'SunOS')
    OS='Solaris'
    ;;
  'AIX') ;;
  *) ;;
esac

# Install software
echo "› $ZSH/script/install"
"$ZSH/script/install"

# Upgrade nvm
echo "› update nvm"
cd "$NVM_DIR" && git pull origin master && git checkout `git describe --abbrev=0 --tags`

# Upgrade apex
apex upgrade
