#!/bin/sh
#
# update
#
# `update` handles installation, updates, things like that. Run it
# periodically to make sure you're on the latest and greatest.
export ZSH="$HOME/.dotfiles"

# Set OS defaults
"$ZSH/osx/set-defaults.sh"

# Install homebrew
"$ZSH/homebrew/install.sh" 2>&1

# Install software
echo "› $ZSH/script/install"
"$ZSH/script/install"

# Upgrade nvm
echo "› update nvm"
cd "$NVM_DIR" && git pull origin master && git checkout `git describe --abbrev=0 --tags`

# Upgrade apex
apex upgrade
